### ISSUE TITLE
"Previous" Exceptions

### ISSUE THREAD

**Issue by PHLAK** [spatie/flareapp.io-roadmap#24]
As far as I can tell when an exception is thrown (and sent to Flare) that contains a "previous" exception there's no way to view the previous exception from the Flare UI. 

For example, given the following

```php
try {
    // Something that throws an exception
} catch (SomeException $exception) {
    throw AnotherException('Message', 0, $exception); // Note the third parameter here
}
```

there's no way to access/view the contents (e.g. message, code, etc. ) of `SomeExcption`.

For reference you can access the previous exception (and it's related data) through the [`getPrevious()`](https://www.php.net/manual/en/exception.getprevious.php) method on an Exception class.

```php
$someException = new Exception('First exception');

$anotherException = new Exception('Second exception', 0, $someException);

$anotherException->getPrevious()->getMessage(); // Returns 'First exception'
```

It would be extremely useful to be able to access the previous exception via the UI either in the Stack trace tab or via a dedicated tab.

**Comment by AlexVanderbist** [comment]
Hi @PHLAK, thanks for the suggestion! This is one of the things we're currently working on. Looking forward to sharing more soon :)
