### ISSUE TITLE
Use ISO 8601 for dates in Slack notifications

### ISSUE THREAD

**Issue by markjaquith** [spatie/flareapp.io-roadmap#31]
When I snooze an error in Slack, it says `mark snoozed error until 06.05.2021 23:49`
(Meaning May 6th... today).

This date format is confusing to Americans.

Could you use ISO 8601 (2021-06-05) which is a non-ambiguous, internationally-recognized format?

**Comment by freekmurze** [comment]
Thanks for your suggestion, I've changed the date format to ISO 8601 👍
