### ISSUE TITLE
Option to delete or resolve all (open) errors in a project

### ISSUE THREAD

**Issue by AlexVanderbist** [spatie/flareapp.io-roadmap#6]
Probably implemented as a couple of buttons in the project settings (cfr. GitHub)

**Comment by andreladocruz** [comment]
Add here should be great too =) 

![image](https://user-images.githubusercontent.com/3315596/110950326-9d484380-833b-11eb-86ef-f2e034bad0e1.png)

**Comment by AlexVanderbist** [comment]
We've now got a separate flow to select **all** errors to delete/snooze/resolve :)
![image](https://user-images.githubusercontent.com/6287961/122175898-4eeb9900-ce84-11eb-805d-d75bf1cd02c3.png)
